# Generated by Django 3.1.6 on 2021-02-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsapi',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newsapi',
            name='content',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='newsapi',
            name='newstitle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newsapi',
            name='source',
            field=models.CharField(max_length=255),
        ),
    ]
