# Generated by Django 3.1.6 on 2021-02-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsAPI', '0002_auto_20210225_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsapi',
            name='newstitle',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
