# Generated by Django 3.1.6 on 2021-02-28 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsAPI', '0005_auto_20210228_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsapi',
            name='save',
            field=models.ManyToManyField(blank=True, related_name='save_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
