# Generated by Django 3.1.6 on 2021-03-01 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsAPI', '0006_auto_20210228_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsapi',
            name='save',
        ),
        migrations.CreateModel(
            name='Savenewsapi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsAPI.newsapi')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
