# Generated by Django 3.1.6 on 2021-03-01 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsAPI', '0007_auto_20210301_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsapi',
            name='save',
            field=models.ManyToManyField(blank=True, related_name='save_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Savenewsapi',
        ),
    ]
