# Generated by Django 3.1.6 on 2021-03-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsAPI', '0009_auto_20210301_1331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Savenewsapi',
        ),
    ]
