# Generated by Django 3.1.6 on 2021-03-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsAPI', '0011_newsapi_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsapi',
            name='favourite',
        ),
    ]
