# Generated by Django 3.1.6 on 2021-03-01 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsAPI', '0012_remove_newsapi_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsapi',
            name='favourite',
            field=models.ManyToManyField(related_name='news_favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
